---
title: "Notebook"
author: "Alessio Mezzina"
date: "2024-03-26"
output:
  html_document: default
  word_document: default
  pdf_document: default
---
```{r}
rm(list = ls())
```

```{r}
library(ggplot2)
library(ggraph)
library(grid)
library(igraph)
library(muxViz)
library(RColorBrewer)
library(viridis)

```

```{r}
#Lettura del grafo completo
grafo <- read_graph("multilayer.graphml", format = "graphml")


nodi_e_layer <- strsplit(V(grafo)$id, split = "', '", fixed = TRUE)
nomi_nodi <- unique(sapply(nodi_e_layer, function(x) gsub("[()']", "", x[1])))
tipi_layer <- unique(sapply(nodi_e_layer, function(x) gsub("[')]", "", x[2])))

# Aggiungi un attributo 'name' a ciascun nodo nel grafo originale contenente solo il nome del gene
V(grafo)$name <- sapply(V(grafo)$id, function(id) {
  # Estrai solo il nome del gene dall'ID del nodo
  nome_gene <- gsub("[()']", "", strsplit(id, ", ")[[1]][1])
  nome_gene
})

# Prepara un set completo di nodi per ogni tipo di layer
nodi_completi_per_layer <- expand.grid(nomi_nodi, tipi_layer)
colnames(nodi_completi_per_layer) <- c("nome", "layer")

sottografi <- list()
for (layer in tipi_layer) {
  # Crea un sottografo vuoto
  sottografo <- make_empty_graph(n = length(nomi_nodi))
  # Assegna i nomi dei nodi
  V(sottografo)$name <- nomi_nodi
  # Salva il sottografo inizializzato
  sottografi[[layer]] <- sottografo
}

# precalcolo degli indici
indice_nodi <- list()
for(layer in tipi_layer) {
  nomi_nodi_layer_specifici <- V(sottografi[[layer]])$name
  indice_nodi[[layer]] <- setNames(seq_along(nomi_nodi_layer_specifici), nomi_nodi_layer_specifici)
}

# Imposta la directory in cui cercare/salvare i sottografi
directory_salvataggio <- "./"

# Inizializza la lista dei sottografi
sottografi <- list()

# Prova a caricare i sottografi esistenti per ogni layer
caricati_con_successo <- TRUE
for(layer in tipi_layer) {
  percorso_file <- paste0(directory_salvataggio, "sottografo_", layer, ".graphml")
  
  if(file.exists(percorso_file)) {
    sottografi[[layer]] <- read_graph(percorso_file, format = "graphml")
  } else {
    caricati_con_successo <- FALSE
    break
  }
}

# Se non tutti i sottografi sono stati caricati, esegui il ciclo for per generarli
if(!caricati_con_successo) {
  cat("Non tutti i sottografi esistono. Generazione dei sottografi in corso...\n")
  
  # (Re)inizializza i sottografi se necessario
  # Questo passaggio dipende da come vuoi gestire la situazione in cui alcuni sottografi esistono e altri no
  # Qui li reinizializziamo tutti per semplicità
  sottografi <- list()
  for(layer in tipi_layer) {
    sottografo <- make_empty_graph(n = length(nomi_nodi))
    V(sottografo)$name <- nomi_nodi
    sottografi[[layer]] <- sottografo
  }
  
  # Inserisci qui il codice per popolare i sottografi, come il ciclo for sopra
  for(e in E(grafo)) {
    if(e %% 100 == 0) {
    cat("arco: ", e)
  }
  nodi_ends <- ends(grafo, e)
  sorgente <- V(grafo)[nodi_ends[1]]$name
  destinazione <- V(grafo)[nodi_ends[2]]$name
  tipo_layer <- E(grafo)[e]$type
  if(tipo_layer != "interlayer") {
    indice_sorgente <- indice_nodi[[tipo_layer]][sorgente]
    indice_destinazione <- indice_nodi[[tipo_layer]][destinazione]
    sottografi[[tipo_layer]] <- add_edges(sottografi[[tipo_layer]], c(indice_sorgente, indice_destinazione))
  }
  }
  
  # Dopo la generazione, salva i nuovi sottografi per un uso futuro
  for(layer in tipi_layer) {
    percorso_file <- paste0(directory_salvataggio, "sottografo_", layer, ".graphml")
    write_graph(sottografi[[layer]], percorso_file, format = "graphml")
  }
}
```

# Utilizzo di MuxVizR
```{r}
#Network setup
Layers <- 3
layerCouplingStrength <- 1
networkOfLayersType <- "categorical"
layer.colors <- brewer.pal(3, "Set2")

nodeTensor <- list()
g.list <- sottografi
for(l in 1:Layers){
  nodeTensor[[l]] <- igraph::as_adjacency_matrix(g.list[[l]])
}
NodesTensor <- nodeTensor

#Define the network of layers
layerTensor <-
  BuildLayersTensor(
    Layers = Layers,
    OmegaParameter = layerCouplingStrength,
    MultisliceType = networkOfLayersType
  )
layerLabels <- 1:Layers
```

```{r}
#Build the multilayer adjacency tensor
isDirected = F
Nodes <- vcount(sottografi[[1]])  # Utilizza il primo sottografo come riferimento
M <- BuildSupraAdjacencyMatrixFromEdgeColoredMatrices(nodeTensor, layerTensor, Layers, Nodes)
SupraAdjacencyMatrix <- M
```

# Calcolo della centralità
```{r}
MultiDegree <- GetMultiDegree(SupraAdjacencyMatrix, Layers, Nodes, isDirected)
```

```{r}
MultiDegreeSum <- GetMultiDegreeSum(SupraAdjacencyMatrix, Layers, Nodes, isDirected)
```

```{r}
MultiPageRankCentrality <- GetMultiPageRankCentrality(SupraAdjacencyMatrix, Layers, Nodes)
```

# Clustering
```{r}
pathInfomap <- "./Infomap"
MultilayerCommunities_Infomap <- GetMultilayerCommunities_Infomap(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  bin.path = pathInfomap,
  isDirected,
  seed = 12345,
  includeSelfLinks = F,
  numTrials = 100,
  twoLevel = T,
  preclusterMultiplex = F,
  addMissingPhysicalNodes = T,
  hardPartitions = F,
  verbose = T,
  addAggregateAnalysis = T,
  outputPrefix = "multimap"
)
```
# Data Visualization and Plotting

```{r}
print(MultiDegree)
print(MultiDegreeSum)
print(MultiPageRankCentrality)
print(MultilayerCommunities_Infomap)
```

```{r}
g <- sottografi[[1]]

V(g)$centralita <- MultiDegree

# Ora, per visualizzare il grafo con ggraph:
library(ggraph)
library(igraph)

# Utilizza un layout che preferisci, ad esempio 'fr' per Fruchterman-Reingold
ggraph(g, layout = "fr") +
  geom_edge_link(color = "gray50", alpha = 0.5) + # Rendi gli archi meno dominanti
  geom_node_point(aes(size = centralita), alpha = 0.8, color = "steelblue") + # Dimensioni dei nodi basate sulla centralità
  geom_node_text(aes(label = name), vjust = 1.5, size = 3, color = "darkred") + # Opzionale: aggiunge etichette ai nodi
  scale_size(range = c(1, 10)) + # Adatta questo per controllare il range di dimensioni dei nodi
  theme_void() + # Rimuove elementi non necessari dallo sfondo
  labs(title = "Visualizzazione del Grafo con Centralità dei Nodi")


ggraph(g, layout = "fr") +
  geom_edge_link(color = "gray50", alpha = 0.5) + # Rendi gli archi meno dominanti
  geom_node_point(aes(size = centralita), alpha = 0.8, color = "steelblue") + # Dimensioni dei nodi basate sulla centralità
  scale_size(range = c(1, 10)) + # Adatta questo per controllare il range di dimensioni dei nodi
  theme_void() + # Rimuove elementi non necessari dallo sfondo
  labs(title = "Visualizzazione del Grafo con Centralità dei Nodi")
```
```{r}
# Utilizza un layout che aiuti a evitare la sovrapposizione
ggraph(g, layout = 'fr') +
  geom_edge_link(color = "gray50", alpha = 0.5) + # Rendi gli archi meno dominanti
  geom_node_point(aes(size = centralita), alpha = 0.8, color = "steelblue") + # Dimensioni dei nodi basate sulla centralità
  geom_node_text(aes(label = etichetta), check_overlap = TRUE, vjust = 1.5, size = 3, color = "darkred", na.rm = TRUE) + # Etichette solo per nodi selezionati
  scale_size(range = c(1, 10)) + # Adatta questo per controllare il range di dimensioni dei nodi
  theme_void() + # Rimuove elementi non necessari dallo sfondo
  labs(title = "Visualizzazione del Grafo con Centralità dei Nodi")
```

```{r}
library(tidyverse)

# Trasforma MultiDegree in un dataframe
df_centralita <- as.data.frame(MultiDegree) %>%
  rownames_to_column(var = "Nodo") %>%
  pivot_longer(cols = -Nodo, names_to = "Layer", values_to = "Centralità")

# Plotta il grafico a barre
ggplot(df_centralita, aes(x = Nodo, y = Centralità, fill = Layer)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Centralità MultiDegree per Nodo e Layer",
       x = "Nodo",
       y = "Centralità") +
  scale_fill_viridis_d()

```

```{r}
# Converti 'MultilayerCommunities_Infomap$membership.multi' in un dataframe per la manipolazione
community_data <- as.data.frame(MultilayerCommunities_Infomap$membership.multi)

# Rinomina le colonne per chiarezza, se necessario
community_data <- rename(community_data, Comunità = module, Nodo = node, Layer = layer)

# Poiché abbiamo più sottografi, potresti voler aggiungere l'informazione della comunità a ogni nodo in ogni layer.
# Nota: Questo esempio assume che l'ID del nodo e il layer siano coerenti attraverso i sottografi.
for(layer in names(sottografi)) {
  for(i in seq_len(vcount(sottografi[[layer]]))) {
    nodo_name <- V(sottografi[[layer]])[i]$name
    layer_number <- which(names(sottografi) == layer)
    
    # Trova la comunità del nodo corrente basandosi su 'node' e 'layer'
    comunità_nodo <- community_data$Comunità[community_data$Nodo == i & community_data$Layer == layer_number]
    
    if(length(comunità_nodo) > 0) {
      V(sottografi[[layer]])[i]$community <- comunità_nodo
    } else {
      V(sottografi[[layer]])[i]$community <- NA # Assign NA se il nodo non ha una comunità assegnata in questo layer
    }
  }
}

# Ora puoi visualizzare uno dei sottografi con le comunità colorate
library(ggraph)
library(igraph)

g <- sottografi[[1]] # Scegli quale layer visualizzare

ggraph(g, layout = 'fr') +
  geom_edge_link(color = "gray80", alpha = 0.5) + # Rendi gli archi meno dominanti
  geom_node_point(aes(color = as.factor(community)), size = 5, alpha = 0.8) + # Regola la dimensione e l'opacità dei nodi
  geom_node_text(aes(label = name), vjust = 1.8, size = 0.5, color = "black") + # Aggiungi etichette con una leggera regolazione verticale
  scale_color_viridis_d() + # Utilizza una scala di colori distintiva
  theme_graph(base_size = 12) + # Imposta la dimensione base del testo per il grafico
  labs(color = "Comunità") + # Etichetta la legenda
  ggtitle("Visualizzazione del Grafo Multilayer [Expression] con Comunità e Nomi dei Nodi") # Titolo del grafico

g <- sottografi[[2]] # Scegli quale layer visualizzare

ggraph(g, layout = 'fr') +
  geom_edge_link(color = "gray80", alpha = 0.5) + # Rendi gli archi meno dominanti
  geom_node_point(aes(color = as.factor(community)), size = 5, alpha = 0.8) + # Regola la dimensione e l'opacità dei nodi
  geom_node_text(aes(label = name), vjust = 1.8, size = 0.5, color = "black") + # Aggiungi etichette con una leggera regolazione verticale
  scale_color_viridis_d() + # Utilizza una scala di colori distintiva
  theme_graph(base_size = 12) + # Imposta la dimensione base del testo per il grafico
  labs(color = "Comunità") + # Etichetta la legenda
  ggtitle("Visualizzazione del Grafo Multilayer [Methylation] con Comunità e Nomi dei Nodi") # Titolo del grafico

g <- sottografi[[3]] # visualizer quale layer visualizzare

ggraph(g, layout = 'fr') +
  geom_edge_link(color = "gray80", alpha = 0.5) + # Rendi gli archi meno dominanti
  geom_node_point(aes(color = as.factor(community)), size = 5, alpha = 0.8) + # Regola la dimensione e l'opacità dei nodi
  geom_node_text(aes(label = name), vjust = 1.8, size = 0.5, color = "black") + # Aggiungi etichette con una leggera regolazione verticale
  scale_color_viridis_d() + # Utilizza una scala di colori distintiva
  theme_graph(base_size = 12) + # Imposta la dimensione base del testo per il grafico
  labs(color = "Comunità") + # Etichetta la legenda
  ggtitle("Visualizzazione del Grafo Multilayer [Mutation] con Comunità e Nomi dei Nodi") # Titolo del grafico
```