---
title: "Multi Layer Graph Analysis"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(ggraph)
library(grid)
library(igraph)
library(muxViz)
library(RColorBrewer)
library(progress)
```

```{r}
rm(list = ls())
#Lettura del grafo completo
grafo <- read_graph("multilayer.graphml", format = "graphml")
```

```{r}
# Estrai i tipi di layer e i nomi dei nodi utilizzando l'ID del nodo, pulendo i dati in un unico passaggio
nodi_e_layer <- strsplit(V(grafo)$id, split = "', '", fixed = TRUE)
nomi_nodi <- unique(sapply(nodi_e_layer, function(x) gsub("[()']", "", x[1])))
tipi_layer <- unique(sapply(nodi_e_layer, function(x) gsub("[')]", "", x[2])))

# Stampa per verifica
print(head(nomi_nodi))
print(tipi_layer)
```

```{r}
# Aggiungi un attributo 'name' a ciascun nodo nel grafo originale contenente solo il nome del gene
V(grafo)$name <- sapply(V(grafo)$id, function(id) {
  # Estrai solo il nome del gene dall'ID del nodo
  nome_gene <- gsub("[()']", "", strsplit(id, ", ")[[1]][1])
  nome_gene
})

# Verifica che l'attributo 'name' sia stato aggiunto correttamente
head(V(grafo)$name)
```

```{r}
# Prepara un set completo di nodi per ogni tipo di layer
nodi_completi_per_layer <- expand.grid(nomi_nodi, tipi_layer)
colnames(nodi_completi_per_layer) <- c("nome", "layer")
```

```{r}
sottografi <- list()
for (layer in tipi_layer) {
  # Crea un sottografo vuoto
  sottografo <- make_empty_graph(n = length(nomi_nodi))
  # Assegna i nomi dei nodi
  V(sottografo)$name <- nomi_nodi
  # Salva il sottografo inizializzato
  sottografi[[layer]] <- sottografo
}
```

```{r}
# precalcolo degli indici
indice_nodi <- list()
for(layer in tipi_layer) {
  nomi_nodi_layer_specifici <- V(sottografi[[layer]])$name
  indice_nodi[[layer]] <- setNames(seq_along(nomi_nodi_layer_specifici), nomi_nodi_layer_specifici)
}
```

```{r}
# Imposta la directory in cui cercare/salvare i sottografi
directory_salvataggio <- "./"

# Inizializza la lista dei sottografi
sottografi <- list()

# Prova a caricare i sottografi esistenti per ogni layer
caricati_con_successo <- TRUE
for(layer in tipi_layer) {
  percorso_file <- paste0(directory_salvataggio, "sottografo_", layer, ".graphml")
  
  if(file.exists(percorso_file)) {
    sottografi[[layer]] <- read_graph(percorso_file, format = "graphml")
  } else {
    caricati_con_successo <- FALSE
    break
  }
}

# Se non tutti i sottografi sono stati caricati, esegui il ciclo for per generarli
if(!caricati_con_successo) {
  cat("Non tutti i sottografi esistono. Generazione dei sottografi in corso...\n")
  
  # (Re)inizializza i sottografi se necessario
  # Questo passaggio dipende da come vuoi gestire la situazione in cui alcuni sottografi esistono e altri no
  # Qui li reinizializziamo tutti per semplicità
  sottografi <- list()
  for(layer in tipi_layer) {
    sottografo <- make_empty_graph(n = length(nomi_nodi))
    V(sottografo)$name <- nomi_nodi
    sottografi[[layer]] <- sottografo
  }
  
  # Inserisci qui il codice per popolare i sottografi, come il ciclo for sopra
  for(e in E(grafo)) {
    if(e %% 100 == 0) {
    cat("arco: ", e)
  }
  nodi_ends <- ends(grafo, e)
  sorgente <- V(grafo)[nodi_ends[1]]$name
  destinazione <- V(grafo)[nodi_ends[2]]$name
  tipo_layer <- E(grafo)[e]$type
  if(tipo_layer != "interlayer") {
    indice_sorgente <- indice_nodi[[tipo_layer]][sorgente]
    indice_destinazione <- indice_nodi[[tipo_layer]][destinazione]
    sottografi[[tipo_layer]] <- add_edges(sottografi[[tipo_layer]], c(indice_sorgente, indice_destinazione))
  }
  }
  
  # Dopo la generazione, salva i nuovi sottografi per un uso futuro
  for(layer in tipi_layer) {
    percorso_file <- paste0(directory_salvataggio, "sottografo_", layer, ".graphml")
    write_graph(sottografi[[layer]], percorso_file, format = "graphml")
  }
} else {
  cat("Tutti i sottografi sono stati caricati con successo.\n")
}
```

```{r}
# verifiche
# Stampa il numero di nodi e archi per ciascun sottografo
lapply(sottografi, function(g) {
  list(numero_nodi = gorder(g), numero_archi = gsize(g))
})

# Verifica la presenza di un nodo specifico in un sottografo
nome_nodo_specifico <- "('nome_gene', 'expression')"
layer = "expression" # Assicurati di sostituire 'nome_gene' con un nome di gene valido e 'expression' con il layer corretto
if(nome_nodo_specifico %in% V(sottografi[[layer]])$id) {
  print(paste("Il nodo", nome_nodo_specifico, "è presente nel sottografo", layer))
} else {
  print(paste("Il nodo", nome_nodo_specifico, "NON è presente nel sottografo", layer))
}

# Controlla alcuni archi per un sottografo specifico
head(E(sottografi[[layer]]))
```

```{r}
#Salvataggio sottografi
directory_salvataggio <- "./"
# Cicla attraverso i sottografi e salvali come file GraphML
for(layer in names(sottografi)) {
  percorso_file <- paste0(directory_salvataggio, "sottografo_", layer, ".graphml")
  write_graph(sottografi[[layer]], percorso_file, format = "graphml")
}
```

```{r}
#Inizio analisi con MuxVizR
#Network setup
Layers <- 3
layerCouplingStrength <- 1
networkOfLayersType <- "categorical"
layer.colors <- brewer.pal(3, "Set2")
```

```{r}
nodeTensor <- list()
g.list <- sottografi
for(l in 1:Layers){
  nodeTensor[[l]] <- igraph::get.adjacency(g.list[[l]])
}
```

```{r}
#Define the network of layers
layerTensor <-
  BuildLayersTensor(
    Layers = Layers,
    OmegaParameter = layerCouplingStrength,
    MultisliceType = networkOfLayersType
  )
layerLabels <- 1:Layers
```

```{r}
#Build the multilayer adjacency tensor
Nodes <- vcount(sottografi[[1]])  # Utilizza il primo sottografo come riferimento
M <- BuildSupraAdjacencyMatrixFromEdgeColoredMatrices(nodeTensor, layerTensor, Layers, Nodes)
SupraAdjacencyMatrix <- M
isDirected = F
#Una matrice di adiacenza supra o "supra-adjacency matrix" è un modo per rappresentare un grafo multistrato in una singola matrice quadrata. In pratica, è una matrice di adiacenza che combina le informazioni di tutti gli strati in un'unica struttura. Questa matrice è divisa in blocchi in modo tale che ogni blocco rappresenti le connessioni intra-layer o inter-layer. Le connessioni intra-layer sono rappresentate da blocchi sulla diagonale principale della matrice, mentre le connessioni inter-layer possono essere rappresentate da blocchi fuori dalla diagonale.
```

#Testing delle funzioni
```{r}
#Building multilayer networks
SampleMultiplex <- GetSampleMultiplex(Layers, Nodes, 3)
print(SampleMultiplex)
```

```{r}
#Building multilayer networks
ExtendedEdgelistFromSupraAdjacencyMatrix <- BuildExtendedEdgelistFromSupraAdjacencyMatrix(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  isDirected
)
print(ExtendedEdgelistFromSupraAdjacencyMatrix)
```

```{r}
#Building multilayer networks
SupraAdjacencyMatrixFromEdgeColoredMatricesTMP <- BuildSupraAdjacencyMatrixFromEdgeColoredMatrices(
  NodesTensor,
  LayerTensor,
  Layers,
  Nodes
)
print(SupraAdjacencyMatrixFromEdgeColoredMatricesTMP)
```

```{r}
#Building multilayer networks
SupraAdjacencyToBlockTensortmp <- SupraAdjacencyToBlockTensor(SupraAdjacencyMatrix, Layers, Nodes)
print(SupraAdjacencyToBlockTensortmp)
```

```{r}
#Building multilayer networks
print(SupraAdjacencyToNetworkList(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
#Building multilayer networks
print(SupraAdjacencyToNodesTensor(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
#Aggregation functions
print(GetAggregateMatrix(NodesTensor, Layers, Nodes))
```
```{r}
print(GetAggregateMatrixFromNetworkList(sottografi))
```

```{r}
#Aggregation functions
GetAggregateMatrixFromSupraAdjacencyMatrix(SupraAdjacencyMatrix, Layers, Nodes)
```

```{r}
print(GetAggregateNetworkFromNetworkList(sottografi))
```

```{r}
print(GetAggregateNetworkFromSupraAdjacencyMatrix(
  SupraAdjacencyMatrix,
  Layers,
  Nodes
))
```

# Centralities
```{r}
print(GetMultiAuthCentrality(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetMultiClosenessCentrality(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetMultiDegree(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiDegreeSum(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
MultiEigenvectorCentrality <- GetMultiEigenvectorCentrality(SupraAdjacencyMatrix, Layers, Nodes)
```

```{r}
print(GetMultiHubCentrality(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetMultiInDegree(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiInDegreeSum(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiInStrength(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiInStrengthSum(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiKCoreCentrality(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
MultiKatzCentrality <- GetMultiKatzCentrality(SupraAdjacencyMatrix, Layers, Nodes)
```

```{r}
print(GetMultiOutDegree(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiOutDegreeSum(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiOutStrength(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiOutStrengthSum(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiPageRankCentrality(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetMultiPathStatistics(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetMultiRWCentrality(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  Type = "classical",
  Method = "multilayer"
))
```

```{r}
print(GetMultiStrength(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiStrengthSum(SupraAdjacencyMatrix, Layers, Nodes, isDirected))
```

```{r}
print(GetMultiplexityCentrality(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetConnectedComponents(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetGiantConnectedComponent(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetGiantIntersectionComponent(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetGiantIntersectionComponentFromNetworkList(sottografi))
```

```{r}
print(GetGiantViableComponent(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetGiantViableComponentFromNetworkList(sottografi))
```

```{r}
MultilayerCommunities_Infomap = GetMultilayerCommunities_Infomap(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  bin.path = NA, #bin.path path, full path where the INFOMAP binary executable is located, (non so cosa sia INFOMAP e nella documentazione non è presente)
  isDirected,
  seed = 12345,
  includeSelfLinks = F,
  numTrials = 100,
  twoLevel = T,
  preclusterMultiplex = F,
  addMissingPhysicalNodes = T,
  hardPartitions = F,
  verbose = T,
  addAggregateAnalysis = T,
  outputPrefix = "multimap"
)
print()
```

```{r}
print(GetMultiplexCommunities_Infomap(
  g.list,
  bin.path = NA,
  isDirected,
  seed = 12345,
  includeSelfLinks = F,
  numTrials = 100,
  twoLevel = T,
  preclusterMultiplex = F,
  addMissingPhysicalNodes = T,
  hardPartitions = F,
  verbose = T,
  addAggregateAnalysis = T,
  multilayerRelaxRate = NA,
  multilayerJSRelaxRate = NA,
  outputPrefix = "multimap"
))
```

```{r}
print(GetMultilayerMotifs(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  bin.path = NA,
  motifSize = 3,
  motifSamples = 1e+05,
  isDirected = FALSE,
  motifNullModel = "Local const",
  randomNetworks = 1000,
  randomExchangePerEdges = 3,
  randomExchangeAttempts = 3
))
```

```{r}
print(GetMultilayerMotifsFromNetworkList(
  g.list,
  bin.path = NA,
  motifSize = 3,
  motifSamples = 1e+05,
  isDirected = FALSE,
  motifNullModel = "Local const",
  randomNetworks = 1000,
  randomExchangePerEdges = 3,
  randomExchangeAttempts = 3
))
```

```{r}
print(GetMonoplexTriads(grafo))
```

```{r}
print(GetMultiplexTriads(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetMultiplexTriadsFromNetworkList(sottografi, g.agg = NULL, verbose = T))
```

```{r}
print(GetGlobalNumberTriangles(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetAverageGlobalClustering(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetAverageGlobalNodeOverlappingMatrix(SupraAdjacencyMatrix, Layers, Nodes))
```

```{r}
print(GetAverageGlobalOverlapping(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  fastBinary = F
)
)
```

```{r}
print(GetAverageGlobalOverlappingMatrix(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  fastBinary = F
))
```

```{r}
print(BuildSupraTransitionMatrixFromSupraAdjacencyMatrix(
  SupraAdjacencyMatrix,
  Layers,
  Nodes,
  Type = "pagerank",
  r = NULL
))
```

```{r}
print(BuildTransitionMatrixFromEdgeColoredMatrices(
  NodesTensor,
  Layers,
  Nodes,
  Type = "classical"
))
```

#ALTRO
```{r}
#Get the nodes in the largest connected component
lcc <- GetGiantConnectedComponent(M, Layers, Nodes)

#GetGiantConnectedComponent
#In teoria delle reti, la componente connessa gigante (GCC, Giant Connected Component) è la componente connessa più grande in un grafo, ovvero il sottoinsieme più grande di nodi tutti raggiungibili tra loro attraverso i percorsi nel grafo. In un contesto multistrato, questa funzione probabilmente cerca la GCC considerando la connettività complessiva attraverso tutti gli strati. Ciò significa identificare il gruppo più grande di nodi che rimane connesso quando si considerano le connessioni in tutti gli strati del grafo.

```

```{r}
NodesTensor <- nodeTensor


#Aggregation functions
#Obtaining aggregated networks from multilayes.


AggregateMatrix <- GetAggregateMatrix(NodesTensor, Layers, Nodes) #Get aggregate matrix from nodes tensor

AggregateMatrixFromNetworkList <- GetAggregateMatrixFromNetworkList(g.list) #Get aggregate Matrix from network List

#AggregateMatrixFromSupraAdjacencyMatrix <- GetAggregateMatrixFromSupraAdjacencyMatrix(SupraAdjacencyMatrix, Layers, Nodes) # QUESTA FUNZIONE NON ESISTE

AggregateNetworkFromNetworkList <- GetAggregateNetworkFromNetworkList(g.list) #Get aggregate Network from network List


AggregateNetworkFromSupraAdjacencyMatrix <- GetAggregateNetworkFromSupraAdjacencyMatrix(
  SupraAdjacencyMatrix,
  Layers,
  Nodes
) #Get aggregate network from supra-adjacency matrix


```

```{r}
#Centralities

MultiAuthorityCentrality <- GetMultiAuthCentrality(SupraAdjacencyMatrix, Layers, Nodes) # Not Working
```

```{r}
#Mesoscale structures
SupraAdjacencyMatrix <- M
# Describing and anlysis the mescoscale structure of multilayer networks.
connectedComponents <- GetConnectedComponents(SupraAdjacencyMatrix, Layers, Nodes) #Return the component assignment for each node
GetGiantConnectedComponent(SupraAdjacencyMatrix, Layers, Nodes) #Return the largest connected component

GiantIntersectionComponent <- GetGiantIntersectionComponent(SupraAdjacencyMatrix, Layers, Nodes) #Return the largest connected component obtained by intersecting LCC of each layer. Assumption: the network is an edge-colored multigraph

cat(SupraAdjacencyMatrix)
cat(connectedComponents)
cat(GiantIntersectionComponent)
```

```{r}
#Calculate Global Clustering Coefficient
GloblalClustering <- GetAverageGlobalClustering(SupraAdjacencyMatrix, Layers, Nodes)
cat(GloblalClustering)
```
```{r}
GlobalNumberTriangles <- GetGlobalNumberTriangles(SupraAdjacencyMatrix, Layers, Nodes)
cat(GlobalNumberTriangles)
```
```{r}
AverageGlobalClustering <- GetAverageGlobalClustering(SupraAdjacencyMatrix, Layers, Nodes)
cat(AverageGlobalClustering)
```

```{r}
AverageGlobalNodeOverlappingMatrix <- GetAverageGlobalNodeOverlappingMatrix(SupraAdjacencyMatrix, Layers, Nodes)
cat(AverageGlobalNodeOverlappingMatrix)
```

```{r}
#layoutMultiplex(g.list, layout = "fr", ggplot.format = F, box = T)
plot_multiplex(g.list, layer.colors, edge.colors = "black", node.colors = "auto",
   node.size.values = 0.1, node.alpha = 0.1, edge.alpha = 1, layout = "fr", show.legend = T)
```